version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # ... (остальные команды)
    ports:
      - '9090:9090'
    restart: unless-stopped
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pass
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring_net

  # --- НОВЫЙ СЕРВИС ---
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    # Важно: даем доступ к хосту для сбора метрик
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /sys/class/hwmon:/sys/class/hwmon:ro
      - /sys/devices:/sys/devices:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude="^/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.hwmon'

    ports:
      - '9100:9100'
    restart: unless-stopped
    networks:
      - monitoring_net


  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: olist_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init/init_metrics.sql:/docker-entrypoint-initdb.d/init_metrics.sql # <--- ДОБАВЛЕНО
    networks:
      - monitoring_net

  # --- НОВЫЙ СЕРВИС 2: PostgreSQL Exporter ---
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      # Проще использовать переменную окружения для указания кастомного пути, 
      # если exporter поддерживает PG_EXPORTER_EXTEND_QUERY_PATH (что обычно так)
      - DATA_SOURCE_NAME=postgresql://postgres:123456@db:5432/olist_db?sslmode=disable
      - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/postgres_exporter/custom_queries.yaml # <--- ИЗМЕНЕНИЕ 1: Путь к кастомному файлу 
    volumes:
      # <--- ИЗМЕНЕНИЕ 2: Монтирование файла с хоста в контейнер
      - ./custom_queries.yaml:/etc/postgres_exporter/custom_queries.yaml
    ports:
      - '9187:9187'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - monitoring_net

  custom-exporter:
    build: . # Docker будет искать Dockerfile в текущей папке
    container_name: custom_exporter
    ports:
      - "9876:9876" # Порт, на котором работает наш Python-скрипт
    restart: unless-stopped
    networks:
      - monitoring_net

volumes:
  prometheus_data:
  grafana_data:
  postgres_data:


networks:
  monitoring_net:
    driver: bridge